### PR TITLE
changed project tile layout

### PR DESCRIPTION
**Pull request by cstn**
Optimized layout or project tiles

### CODE REVIEW

**Comment by co0p** [comment]
thanks for the pull request. could you please elaborate why this fix is necessary / what problem it solves? otherwise looks good

**Comment by cstn** [comment]
This change fixes a layout problem of the project tile reported to me by @AndreasPrang. The stats element should be located at the bottom of the tile.

**Comment by AndreasPrang** [comment]
I asked Cstn to fix the visualisation in the tails. Works great. 
Thanks.

**Comment by co0p** [comment]
ah. makes sense. 

since this is a group effort I ask kindly to report bugs and new feature requests as github issues, describing the problem and wanted behaviour. 

then someone can do a fix referencing the issue number in the commit message. this way everyone involved knows what is going on. 

carsten, glad to have you on board.

**Comment by AndreasPrang** [comment]
👍

**Pull request merged**
